### ISSUE TITLE
Heisenbug 2017 Piter Conference

### ISSUE THREAD

**Issue by bestosma** [ckenst/ama#2]
Hello Chris!

Last week I contributed information about a QA-conference "Heisenbug 2017 Piter" orginized by the company I work for. That's the website of the conference: https://heisenbug-piter.ru/en/
It's devoted to testing only - you could see it in the schedule: https://heisenbug-piter.ru/en/#schedule

It seems, that you've decided to left it out. Could you please tell, it you have not liked the program or are there some other reasons?

Thanks a lot in advance for your answer!

With kind regards,
Xenia Lavrova
Marketing dept.
JUG.ru Group
https://jugru.org/en/

**Comment by ckenst** [comment]
@bestosma sorry for the late reply.

Did you submit it as a PR here: https://github.com/TestingConferences/testingconferences.github.io/pulls? If so I didn't see it. Can you re-submit? 

I agree it should be included! 👍

**Comment by bestosma** [comment]
Hi Chris,

I actually clicked the "contribute | source" button in the footer on the http://testingconferences.org/ and added the info here: https://github.com/TestingConferences/testingconferences.github.io/blob/master/_data/current.yml 

The lines I'd added were:

 - name: Heisenbug 2017 Piter
  location: Saint Petersburg, Russia
  dates: "June 4, 2017"
  url: https://heisenbug-piter.ru/en/
  twitter: HeisenbugConf
  status: Registration is open 


Now I proposed this change once again. Please tell, if I should submit the conference in some other place.

Thanks again!

With kind regards,

Xenia

**Comment by ckenst** [comment]
@bestosma Great, that information looks good. Now did submit a Pull Request with those changes? If you are unsure, check out the instructions here: http://testingconferences.org/news/2015/10/29/contribute.htm.  I appreciate you going through this to help out!

**Comment by bestosma** [comment]
@ckenst I unfortunately get error 404 under the link http://testingconferences.org/news/2015/10/29/contribute.htm
Could you please check?

**Comment by ckenst** [comment]
http://testingconferences.org/news/2015/10/29/contribute.html. Missing the last letter. Try again
