### ISSUE TITLE
Software Testing Conferences - new conference

### ISSUE THREAD

**Issue by timetraveler90** [ckenst/ama#4]
Hello there Chris,

I like your idea of having all testing conferences on one spot, so i wanted to share one really good testing conference from Europe that is missing on your list. It is:

**TestCon Vilnius**
[http://www.testcon.lt/](http://www.testcon.lt/)

As you can see on their youtube channel [https://www.youtube.com/user/DATAMINERLT/videos link](https://www.youtube.com/user/DATAMINERLT/videos) they covered some very hot topics in the previous years, so i think it's worth attending it or watching so i wanted to share it with you.

Kind regards and all the best,
Petar Stanisic

**Comment by ckenst** [comment]
@timetraveler90 added! Appreciate the heads up and hope you find the list valuable. Also next time if you get a chance, feel free to just add it yourself as a PR.
