### ISSUE TITLE
Submit a conference

### ISSUE THREAD

**Issue by nscavalleri** [ckenst/ama#5]
Hi Chris, 

How can I submit a conference status en testingconferences.org?
I go to Contribute but then I do not know what to do.

Thank you in advance.
Nadia

**Comment by ckenst** [comment]
Hi Nadia!

Yeah great question. Have you tried these instructions? http://testingconferences.org/news/2015/10/29/contribute.html. Let me know if this helps and/or if it doesn't. I'd love to update them if we figure out what does / doesn't work.

**Comment by ckenst** [comment]
So did the instructions help? Did we miss anything?

**Comment by nscavalleri** [comment]
The steps are fine. But, in the last one, I dind't know how to continue
after pressing the pull request button. Maybe you can add any note in
there. Thank you!

2018-03-20 15:51 GMT-03:00 Chris Kenst <notifications@github.com>:
