### ISSUE TITLE
Request to be added to https://testingconferences.org/

### ISSUE THREAD

**Issue by olgaaleksandra** [ckenst/ama#6]
Hello,
I am contacting you on behalf of Agile & Automation Days conference.
I would like to ask what is the procedure to be addes to https://testingconferences.org/?

Thank you.
Best regards,
Olga Guz. 

tel.: (+48) 533 389 220

http://aadays.pl/

https://www.facebook.com/aadays/

https://twitter.com/AADaysPoland

**Comment by ckenst** [comment]
Hi @olgaaleksandra you would want to create a Pull Request with the changes on [this repo](https://github.com/TestingConferences/testingconferences.github.io). 

I added it for you this time (so check out the site again). If you want to make any changes or add things in the future try following this guide: https://testingconferences.org/news/2015/10/29/contribute.html
