### ISSUE TITLE
Authoring a book on Robotic Process Automation

### ISSUE THREAD

**Issue by herambb2210** [ckenst/ama#7]
Hello Chris, 

My name is Heramb and I work for a publishers called Packt Publishing. We publish books for all levels of I.T. users across Enterprise and Open Source software ( www.packtpub.com if you would like to have a look).

We currently have a book in development titled Robotic Process Automation Projects. The book will be a practical guide for learning the intricacies of RPA with UiPath. The book will explore the inbuilt template to automate the business processes and introduce you to the UiPath Studio to makes automation smoother.

I was wondering if you would be interested in discussing the opportunity to author this title for us? I’ve seen from your blog posts that you are very knowledgeable about this area, and would be delighted if you did want to discuss this opportunity further.

I look forward to hearing from you soon.

Kind regards,
Heramb

**Comment by ckenst** [comment]
Hi @herambb2210. Thanks for thinking of me but I'm not interested at this time. 

- Chris
