### ISSUE TITLE
Any Advice

### ISSUE THREAD

**Issue by CengizCinar** [ckenst/ama#8]
Hi Chris

I want to be a Automation Engineer. Could you give me any advices as a Senior? 

Thanks

Best Regards
Cengiz

**Comment by ckenst** [comment]
Hi Cengiz,

What is your background? What kind of industries do you work in? What kinds of applications have you worked on? Do you have a background in programming? Any kind of existing test automation design?

**Comment by ckenst** [comment]
@CengizCinar since you never responded I'm assuming you got some useful advice? If not hit me up at chris@kenst.com.
